package com.arc.reactor.rag.chunking

import org.springframework.ai.document.Document
import java.util.UUID

/**
 * Splits documents into smaller chunks for improved RAG retrieval accuracy.
 *
 * Short documents (below the configured threshold) are returned as-is.
 * Implementations add chunking metadata (parent_document_id, chunk_index, chunk_total)
 * to each chunk for traceability.
 */
interface DocumentChunker {

    /** Split a single document into one or more chunks. */
    fun chunk(document: Document): List<Document>

    /** Split multiple documents, each independently chunked. */
    fun chunk(documents: List<Document>): List<Document> = documents.flatMap { chunk(it) }

    companion object {
        private const val CHUNK_ID_SEPARATOR = ":chunk:"

        /**
         * Deterministic chunk ID from parent document ID and chunk index.
         * Uses UUID v3 (name-based MD5) to produce valid UUID strings,
         * ensuring compatibility with PgVectorStore which requires UUID format.
         */
        fun chunkId(parentId: String, index: Int): String =
            UUID.nameUUIDFromBytes("$parentId$CHUNK_ID_SEPARATOR$index".toByteArray()).toString()

        /**
         * Derive all possible chunk IDs for a parent document ID.
         * Used at delete time to clean up chunks without an extra search API call.
         */
        fun deriveChunkIds(parentId: String, maxChunks: Int): List<String> =
            (0 until maxChunks).map { chunkId(parentId, it) }

        /** Check if an ID was generated by [chunkId] (valid UUID derived from chunk name). */
        fun isChunkId(id: String): Boolean {
            // A chunk ID is a UUID v3 derived from "parentId:chunk:N".
            // We cannot distinguish it from a random UUID by format alone,
            // so this helper checks if the ID matches any known chunk pattern.
            // For legacy compatibility, also check the old separator format.
            return id.contains(CHUNK_ID_SEPARATOR)
        }
    }
}

/**
 * No-op implementation that returns documents unchanged.
 * Used when chunking is disabled.
 */
class NoOpDocumentChunker : DocumentChunker {
    override fun chunk(document: Document): List<Document> = listOf(document)
}
