package com.arc.reactor.promptlab.analysis

import com.arc.reactor.config.ChatModelProvider
import com.arc.reactor.prompt.PromptTemplateStore
import com.arc.reactor.promptlab.model.FeedbackAnalysis
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import mu.KotlinLogging
import kotlin.coroutines.cancellation.CancellationException

private val logger = KotlinLogging.logger {}

/**
 * 피드백 분석 기반으로 후보 프롬프트 개선안을 생성한다.
 *
 * LLM을 사용하여 기존 강점을 유지하면서 식별된 약점을
 * 보완하는 다양한 프롬프트 변형을 생성한다.
 *
 * WHY: 수동으로 프롬프트를 수정하는 대신, LLM의 메타 프롬프팅 능력을 활용하여
 * 약점을 체계적으로 보완하는 여러 후보를 자동 생성한다.
 * 생성된 후보는 A/B 테스트를 통해 기준 버전과 비교된다.
 *
 * @see FeedbackAnalyzer 약점 분석 제공
 * @see com.arc.reactor.promptlab.ExperimentOrchestrator 후보를 실험에 활용
 */
class PromptCandidateGenerator(
    private val chatModelProvider: ChatModelProvider,
    private val promptTemplateStore: PromptTemplateStore
) {

    private val objectMapper = jacksonObjectMapper()

    /**
     * 식별된 약점을 보완하는 후보 프롬프트 버전을 생성한다.
     *
     * @param templateId 개선할 프롬프트 템플릿 ID
     * @param analysis 식별된 약점이 포함된 피드백 분석 결과
     * @param candidateCount 생성할 후보 프롬프트 수
     * @return 생성된 PromptVersion ID 목록
     * @throws IllegalStateException 활성 버전이 없는 경우
     */
    suspend fun generate(
        templateId: String,
        analysis: FeedbackAnalysis,
        candidateCount: Int = 3
    ): List<String> {
        val activeVersion = promptTemplateStore.getActiveVersion(templateId)
            ?: throw IllegalStateException("No active version for template=$templateId")
        val metaPrompt = buildMetaPrompt(activeVersion.content, analysis, candidateCount)
        val candidates = generateCandidates(metaPrompt, candidateCount)
        val categories = analysis.weaknesses.joinToString(", ") { it.category }
        return candidates.mapNotNull { candidate ->
            val changeLog = "Auto-generated by Prompt Lab: addresses $categories"
            val version = promptTemplateStore.createVersion(templateId, candidate, changeLog)
            version?.id
        }.also { ids ->
            logger.info { "후보 버전 ${ids.size}개 생성 완료: template=$templateId" }
        }
    }

    private suspend fun generateCandidates(prompt: String, count: Int): List<String> {
        val response = callLlm(prompt)
        return parseCandidateResponse(response, count)
    }

    private fun buildMetaPrompt(
        currentPrompt: String,
        analysis: FeedbackAnalysis,
        candidateCount: Int
    ): String {
        val weaknessList = analysis.weaknesses.joinToString("\n") { w ->
            "- ${w.category}: ${w.description} (frequency: ${w.frequency}, examples: ${w.exampleQueries})"
        }
        return """You are a prompt engineering expert. Improve the following system prompt.
            |
            |Current system prompt:
            |---
            |$currentPrompt
            |---
            |
            |Identified weaknesses:
            |$weaknessList
            |
            |Instructions:
            |1. Improve the system prompt to address each weakness while preserving existing strengths
            |2. Generate $candidateCount distinct improvement strategies
            |3. Each candidate should be a complete, standalone system prompt
            |
            |Respond with a JSON array of $candidateCount prompt strings only:
            |["improved prompt 1", "improved prompt 2", ...]""".trimMargin()
    }

    private suspend fun callLlm(prompt: String): String {
        try {
            val client = chatModelProvider.getChatClient(null)
            return client.prompt().user(prompt).call().content().orEmpty()
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            logger.error(e) { "후보 생성 중 LLM 호출 실패" }
            return ""
        }
    }

    private fun parseCandidateResponse(
        response: String,
        expectedCount: Int
    ): List<String> {
        if (response.isBlank()) return emptyList()
        return try {
            val cleaned = response
                .replace(CODE_FENCE_REGEX, "").trim()
            val tree = objectMapper.readTree(cleaned)
            if (!tree.isArray) return emptyList()
            tree.map { it.asText() }
                .filter { it.isNotBlank() }
                .take(expectedCount)
        } catch (e: Exception) {
            logger.warn(e) { "LLM 후보 응답 파싱 실패" }
            emptyList()
        }
    }

    companion object {
        private val CODE_FENCE_REGEX = Regex("```json\\s*|```\\s*")
    }
}
