package com.arc.reactor.promptlab.model

import java.time.Instant
import java.util.UUID

// ── 실험 수명주기 ──

/** 실험 상태 수명주기 */
enum class ExperimentStatus {
    PENDING, RUNNING, COMPLETED, FAILED, CANCELLED
}

/**
 * 최상위 실험 컨테이너.
 *
 * 실험은 기준(baseline) 프롬프트 버전을 하나 이상의 후보 버전과
 * 테스트 쿼리 집합을 사용하여 3계층 평가 파이프라인을 통해 비교한다.
 *
 * WHY: 프롬프트 변경의 효과를 정량적으로 측정하기 위해
 * 제어된 실험 환경을 제공한다. A/B 테스트 방식으로
 * 기준 대비 후보의 성능 차이를 비교한다.
 *
 * @param id 실험 고유 식별자 (UUID)
 * @param name 실험 이름
 * @param description 실험 설명
 * @param templateId 대상 프롬프트 템플릿 ID
 * @param baselineVersionId 기준 프롬프트 버전 ID
 * @param candidateVersionIds 후보 프롬프트 버전 ID 목록
 * @param testQueries 테스트 쿼리 목록
 * @param evaluationConfig 평가 파이프라인 설정
 * @param model 실험에 사용할 LLM 모델 (null=기본)
 * @param judgeModel LLM 심판 모델 (null=실험 모델과 동일)
 * @param temperature LLM 온도 설정
 * @param repetitions 버전-쿼리 쌍당 반복 횟수
 * @param autoGenerated 자동 생성된 실험 여부
 * @param status 실험 상태
 * @param createdBy 생성자
 * @param createdAt 생성 시각
 * @param startedAt 실행 시작 시각
 * @param completedAt 완료 시각
 * @param errorMessage 실패 시 오류 메시지
 * @see com.arc.reactor.promptlab.ExperimentOrchestrator 실험 실행 엔진
 */
data class Experiment(
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val description: String = "",
    val templateId: String,
    val baselineVersionId: String,
    val candidateVersionIds: List<String>,
    val testQueries: List<TestQuery>,
    val evaluationConfig: EvaluationConfig = EvaluationConfig(),
    val model: String? = null,
    val judgeModel: String? = null,
    val temperature: Double = 0.3,
    val repetitions: Int = 1,
    val autoGenerated: Boolean = false,
    val status: ExperimentStatus = ExperimentStatus.PENDING,
    val createdBy: String = "system",
    val createdAt: Instant = Instant.now(),
    val startedAt: Instant? = null,
    val completedAt: Instant? = null,
    val errorMessage: String? = null
)

/**
 * 실험 평가용 테스트 쿼리.
 *
 * @param query 사용자 입력 텍스트
 * @param intent 쿼리의 인텐트 (평가 규칙 선택에 활용)
 * @param domain 비즈니스 도메인
 * @param expectedBehavior 기대 동작 설명 (LLM 심판에 전달)
 * @param tags 분류/필터링 태그
 */
data class TestQuery(
    val query: String,
    val intent: String? = null,
    val domain: String? = null,
    val expectedBehavior: String? = null,
    val tags: List<String> = emptyList()
)

/**
 * 평가 파이프라인 설정.
 *
 * @param structuralEnabled 구조 평가 활성화 여부
 * @param rulesEnabled 규칙 기반 평가 활성화 여부
 * @param llmJudgeEnabled LLM 심판 활성화 여부
 * @param llmJudgeBudgetTokens LLM 심판 토큰 예산
 * @param customRubric 커스텀 평가 루브릭 (null=기본 루브릭)
 */
data class EvaluationConfig(
    val structuralEnabled: Boolean = true,
    val rulesEnabled: Boolean = true,
    val llmJudgeEnabled: Boolean = true,
    val llmJudgeBudgetTokens: Int = 100_000,
    val customRubric: String? = null
)

// ── 트라이얼 결과 ──

/**
 * 단일 트라이얼 결과 — 프롬프트 버전 x 쿼리 x 반복 하나.
 *
 * @param id 트라이얼 고유 식별자
 * @param experimentId 소속 실험 ID
 * @param promptVersionId 사용된 프롬프트 버전 ID
 * @param promptVersionNumber 프롬프트 버전 번호
 * @param testQuery 테스트 쿼리
 * @param repetitionIndex 반복 인덱스
 * @param response 에이전트 응답 텍스트
 * @param success 에이전트 실행 성공 여부
 * @param errorMessage 실패 시 오류 메시지
 * @param toolsUsed 사용된 도구 목록
 * @param tokenUsage 토큰 사용량 요약
 * @param durationMs 실행 소요 시간 (밀리초)
 * @param evaluations 각 평가 계층의 결과
 * @param executedAt 실행 시각
 */
data class Trial(
    val id: String = UUID.randomUUID().toString(),
    val experimentId: String,
    val promptVersionId: String,
    val promptVersionNumber: Int,
    val testQuery: TestQuery,
    val repetitionIndex: Int = 0,
    val response: String? = null,
    val success: Boolean = false,
    val errorMessage: String? = null,
    val toolsUsed: List<String> = emptyList(),
    val tokenUsage: TokenUsageSummary? = null,
    val durationMs: Long = 0,
    val evaluations: List<EvaluationResult> = emptyList(),
    val executedAt: Instant = Instant.now()
)

/**
 * 단일 트라이얼의 토큰 사용량 집계.
 *
 * @param promptTokens 프롬프트 토큰 수
 * @param completionTokens 완성 토큰 수
 * @param totalTokens 총 토큰 수
 */
data class TokenUsageSummary(
    val promptTokens: Int,
    val completionTokens: Int,
    val totalTokens: Int = promptTokens + completionTokens
)

/**
 * 단일 평가 계층의 결과.
 *
 * @param tier 평가 계층
 * @param passed 합격 여부
 * @param score 점수 (0.0 ~ 1.0)
 * @param reason 판정 사유
 * @param evaluatorName 평가기 이름
 */
data class EvaluationResult(
    val tier: EvaluationTier,
    val passed: Boolean,
    val score: Double,
    val reason: String,
    val evaluatorName: String = tier.name
)

// ── 보고서 모델 ──

/**
 * 실험 비교 보고서.
 *
 * @param experimentId 실험 ID
 * @param experimentName 실험 이름
 * @param generatedAt 보고서 생성 시각
 * @param totalTrials 총 트라이얼 수
 * @param versionSummaries 버전별 집계 통계
 * @param queryComparisons 쿼리별 버전 비교
 * @param recommendation 추천 결과
 */
data class ExperimentReport(
    val experimentId: String,
    val experimentName: String,
    val generatedAt: Instant = Instant.now(),
    val totalTrials: Int,
    val versionSummaries: List<VersionSummary>,
    val queryComparisons: List<QueryComparison>,
    val recommendation: Recommendation
)

/**
 * 버전별 집계 통계.
 *
 * @param versionId 버전 ID
 * @param versionNumber 버전 번호
 * @param isBaseline 기준 버전 여부
 * @param totalTrials 총 트라이얼 수
 * @param passCount 합격 트라이얼 수
 * @param passRate 합격률
 * @param avgScore 평균 점수
 * @param avgDurationMs 평균 소요 시간 (밀리초)
 * @param totalTokens 총 토큰 수
 * @param tierBreakdown 계층별 통계
 * @param toolUsageFrequency 도구 사용 빈도
 * @param errorRate 오류율
 */
data class VersionSummary(
    val versionId: String,
    val versionNumber: Int,
    val isBaseline: Boolean,
    val totalTrials: Int,
    val passCount: Int,
    val passRate: Double,
    val avgScore: Double,
    val avgDurationMs: Double,
    val totalTokens: Int,
    val tierBreakdown: Map<EvaluationTier, TierStats>,
    val toolUsageFrequency: Map<String, Int>,
    val errorRate: Double
)

/**
 * 단일 평가 계층의 합격/불합격 통계.
 *
 * @param passCount 합격 수
 * @param failCount 불합격 수
 * @param passRate 합격률
 * @param avgScore 평균 점수
 */
data class TierStats(
    val passCount: Int,
    val failCount: Int,
    val passRate: Double,
    val avgScore: Double
)

/**
 * 단일 쿼리에 대한 버전별 나란히 비교.
 *
 * @param query 테스트 쿼리
 * @param versionResults 각 버전의 결과
 */
data class QueryComparison(
    val query: TestQuery,
    val versionResults: List<QueryVersionResult>
)

/**
 * 특정 쿼리에 대한 단일 버전의 결과.
 *
 * @param versionId 버전 ID
 * @param versionNumber 버전 번호
 * @param response 응답 텍스트
 * @param passed 전체 합격 여부
 * @param score 평균 점수
 * @param durationMs 소요 시간 (밀리초)
 * @param evaluationDetails 각 계층의 평가 상세
 */
data class QueryVersionResult(
    val versionId: String,
    val versionNumber: Int,
    val response: String?,
    val passed: Boolean,
    val score: Double,
    val durationMs: Long,
    val evaluationDetails: List<EvaluationResult>
)

/**
 * 보고서 추천.
 *
 * @param bestVersionId 최적 버전 ID
 * @param bestVersionNumber 최적 버전 번호
 * @param confidence 추천 신뢰도
 * @param reasoning 추천 근거 설명
 * @param improvements 개선 사항 목록
 * @param warnings 주의 사항 목록
 */
data class Recommendation(
    val bestVersionId: String,
    val bestVersionNumber: Int,
    val confidence: RecommendationConfidence,
    val reasoning: String,
    val improvements: List<String> = emptyList(),
    val warnings: List<String> = emptyList()
)

/**
 * 합격률 차이에 기반한 추천 신뢰도.
 *
 * WHY: 합격률 차이가 클수록 추천의 신뢰도가 높다.
 * 운영자가 추천을 자동 적용할지 수동 검토할지 결정하는 데 활용한다.
 */
enum class RecommendationConfidence {
    /** 합격률 차이 >10% */
    HIGH,

    /** 합격률 차이 5-10% */
    MEDIUM,

    /** 합격률 차이 <5% 또는 데이터 부족 */
    LOW
}

// ── 피드백 분석 모델 ──

/**
 * 프롬프트 템플릿에 대한 부정 피드백 분석 결과.
 *
 * @param totalFeedback 전체 피드백 수
 * @param negativeCount 부정 피드백 수
 * @param weaknesses 식별된 약점 목록
 * @param sampleQueries 테스트용 샘플 쿼리 목록
 * @param analyzedAt 분석 시각
 * @see com.arc.reactor.promptlab.analysis.FeedbackAnalyzer 피드백 분석기
 */
data class FeedbackAnalysis(
    val totalFeedback: Int,
    val negativeCount: Int,
    val weaknesses: List<PromptWeakness>,
    val sampleQueries: List<TestQuery>,
    val analyzedAt: Instant = Instant.now()
)

/**
 * 현재 프롬프트에서 식별된 약점.
 *
 * @param category 약점 카테고리 (예: "short_answer", "missing_sources")
 * @param description 약점 설명
 * @param frequency 발생 빈도
 * @param exampleQueries 약점이 발현된 예시 쿼리
 */
data class PromptWeakness(
    val category: String,
    val description: String,
    val frequency: Int,
    val exampleQueries: List<String>
)
